version: "3.8"

services:
    database:
        container_name: ${DB_CONTAINER_NAME}
        image: postgres:15
        env_file:
            - .env
        ports:
            - ${DB_CONTAINER_PORT}:${DB_CONTAINER_PORT}
        volumes:
            - postgres:/data/postgres

volumes:
    postgres:
